---
apiVersion: v1
kind: Namespace
metadata:
  name: infrastruktur
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: metrics
---
apiVersion: v1
kind: Namespace
metadata:
  name: operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: bibliothek
---
apiVersion: v1
kind: Namespace
metadata:
  name: tracing
---
apiVersion: v1
kind: Namespace
metadata:
  name: ci
---
apiVersion: v1
kind: Namespace
metadata:
  name: nuclio

