---

apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: monitoring
  labels:
    app: kibana
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Kibana"
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: ui
  selector:
    app: kibana

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana
  namespace: monitoring
  labels:
    app: kibana
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: quay.io/containerbootcamp/kibana:v5.3.1
        resources:
          requests:
            cpu: 100m
        env:
          - name: "ELASTICSEARCH_URL"
            value: "https://elasticsearch-log:9200"
          - name: "KIBANA_BASE_URL"
            value: "/api/v1/proxy/namespaces/monitoring/services/kibana"
          - name: KIBANA_HOST
            value: "0.0.0.0"
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
