---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: metrics

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: metrics

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: metrics
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Prometheus"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  ports:
  - port: 9090
    protocol: TCP
  selector:
    prometheus: k8s

---

apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  namespace: metrics
  labels:
    prometheus: k8s
spec:
  replicas: 1
  serviceAccountName: prometheus
  externalUrl: http://127.0.0.1:8001/api/v1/proxy/namespaces/metrics/services/prometheus/
  serviceMonitorSelector:
    matchExpressions:
    - {key: k8s-app, operator: Exists}
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles
      prometheus: k8s
  resources:
    requests:
      # 2Gi is default, but won't schedule if you don't have a node with >2Gi
      # memory. Modify based on your target and time-series count for
      # production use. This value is mainly meant for demonstration/testing
      # purposes.
      memory: 400Mi
  alerting:
    alertmanagers:
    - namespace: monitoring
      name: alertmanager-main
      port: web
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 50Gi
